[project]
name = "gcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google>=3.0.0",
    "google-auth>=2.40.2",
    "litellm>=1.72.0",
    "python-dotenv>=1.1.0",
    "smolagents>=1.17.0",
]
